version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: epynic/do-k8s-challenge-wordpress
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build-push-docker-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build  & Push Docker Image
          command: |
            echo "Docker image build"
            docker build -t "${IMAGE_NAME}:${CIRCLE_BUILD_NUM}" .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push "${IMAGE_NAME}:${CIRCLE_BUILD_NUM}"
            echo "Updating Image tag in k8s"
            sed -e "s/\${IMAGETAG}/${CIRCLE_BUILD_NUM}/" k8s-wordpress.yaml > wordpress-deployment.yaml
      - persist_to_workspace:
          root: .
          paths:
            - ./wordpress-deployment.yaml
  push-k8s-manifest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Update Image k8s
          command: |
            echo "Update k8s image tag"
            git config --global user.email "epynic@gmail.com"
            git config --global user.name "Prasanha Kumar"
            git clone git@github.com:epynic/cdn-on-kubernetes.git
            cp /tmp/workspace/wordpress-deployment.yaml cdn-on-kubernetes/k8s/webserver/wordpress-deployment.yaml
            cd cdn-on-kubernetes 
            git remote set-url origin https://${GITHUB_PASS}@github.com/epynic/cdn-on-kubernetes.git
            git commit --allow-empty -am "Automatic commit CircleCI-wordpress:$CIRCLE_BUILD_NUM"
            git push origin main
workflows:
  version: 2
  build-main:
    jobs:
      - build-push-docker-image:
          filters:
            branches:
              only: main
      - push-k8s-manifest:
          requires:
            - build-push-docker-image
          filters:
            branches:
              only: main
