version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: epynic/do-k8s-challenge-wordpress
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build-dockerhub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build  & Push Docker Image
          command: |
            # docker build -t "${IMAGE_NAME}:${CIRCLE_BUILD_NUM}" .
            # echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            # docker push "${IMAGE_NAME}:${CIRCLE_BUILD_NUM}"
            # echo "Update Image tag in k8s"
            sed -e "s/\${IMAGETAG}/${CIRCLE_BUILD_NUM}/" k8s-wordpress.yaml > wordpress-deployment.yaml
            cat wordpress-deployment.yaml
      - persist_to_workspace:
          root: .
          paths:
            - ./wordpress-deployment.yaml

  push-manifest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Update Image k8s
          command: |
            echo "Committing to GitHub"
            git config user.email "epynic@gmail.com"
            git config user.name "Prasanha Kumar"
            git clone git@github.com:epynic/cdn-on-kubernetes.git
            echo " -------  "
            cat /tmp/workspace/wordpress-deployment.yaml
            echo " -- - -- - -- -- "
            ls
            echo " ========== "
            pwd
            cp /tmp/workspace/wordpress-deployment.yaml cdn-on-kubernetes/k8s/web_server/wordpress-deployment.yaml
            cd cdn-on-kubernetes 
            git commit --allow-empty -am "Automatic commit from CircleCI:$CIRCLE_BUILD_NUM"
            git push origin main
workflows:
  version: 2
  build-master:
    jobs:
      - build-dockerhub:
          filters:
            branches:
              only: main
      - push-manifest:
          requires:
            - build-dockerhub
          filters:
            branches:
              only: main
